import '../../presentation/screen/all_notification/view/notification_screen.dart';
import '../../presentation/screen/all_schema/view/all_schema_screen.dart';
import '../../presentation/screen/all_schema/widgets/pay_now_screen.dart';
import '../../presentation/screen/all_transaction/view/all_transaction.dart';
import '../../presentation/screen/authentication/email_verification/view/email_verification_otp.dart';
import '../../presentation/screen/authentication/sign_up/view/signup_screen.dart';
import '../../presentation/screen/authentication/two_fa_after_login/view/two_fa_verify_otp.dart';
import '../../presentation/screen/authentication/two_fa_verification/view/two_fa_verification.dart';
import '../../presentation/screen/authentication/verify_otp/view/verify_otp.dart';
import '../../presentation/screen/crowd_schema/view/crowd_schema_screen.dart';
import '../../presentation/screen/crowd_schema/widgets/crowd_schema_payment_screen.dart';
import '../../presentation/screen/crowd_schema_history.dart/view/crowd_schema_history_screen.dart';
import '../../presentation/screen/deposit/view/deposit_screen.dart';
import '../../presentation/screen/home/view/home_screen.dart';
import '../../presentation/screen/kyc/view/kyc_screen.dart';
import '../../presentation/screen/my_ticket/view/my_ticket_screen.dart';
import '../../presentation/screen/my_ticket/widgets/add_new_ticket.dart';
import '../../presentation/screen/profile_settings/view/profile_settings_screen.dart';
import '../../presentation/screen/referral/view/referral_screen.dart';
import '../../presentation/screen/rewards/view/rewards_screen.dart';
import '../../presentation/screen/schema_history/view/schema_history_screen.dart';
import '../../presentation/screen/send_money/view/send_money_screen.dart';
import '../../presentation/screen/settings_password_change/view/settings_password_change_screend.dart';
import '../../presentation/screen/wallet_exchange/view/wallet_exchange_screen.dart';
import '../../presentation/screen/withdraw/widgets/add_new_withdraw_account_screen.dart';
import '../../presentation/screen/withdraw/view/withdraw_screen.dart';
import '../../presentation/screen/withdraw/widgets/edit_withdraw_account.dart';

import '../../common/widgets/license_expire/license_expire_page.dart';
import '../../presentation/screen/authentication/change_password/view/change_password_screen.dart';
import '../../presentation/screen/authentication/forgot_password/view/forgot_password_screen.dart';
import '../../presentation/screen/authentication/login/view/login_screen.dart';
import '../../presentation/screen/authentication/onboarding/view/onboarding_screen.dart';
import '../../presentation/screen/authentication/splash/view/splash_screen.dart';
import '../../presentation/screen/dashboard/view/dashboard_screen.dart';
import '../../presentation/screen/ranking_badge/view/ranking_badge_screen.dart';

class RoutesConfig {
  static const splash = SplashScreen();
  static const license = LicenseExpiredPage();
  static const onBoarding = OnboardingScreen();
  static const login = LoginScreen();
  static const signup = SignupScreen();
  static const forgotPassword = ForgotPasswordPage();
  static const verifyOtp = VerifyOtp();
  static const changePassword = ChangePasswordScreen();
  static const dashboard = DashboardScreen();
  static const homeScreen = HomeScreen();
  static const rankingBadge = RankingBadgeScreen();
  static const sendMoney = SendMoneyScreen();
  static const deposit = DepositScreen();
  static const withdraw = WithdrawScreen();
  static const editWithdrawAccount = EditWithdrawAccount();
  static const addNewWithdrawAccount = AddNewWithdrawAccountScreen();
  static const walletExchange = WalletExchangePage();
  static const allSchema = AllSchemaScreen();
  static const crowdSchema = CrowdSchemaScreen();
  static const crowdSchemaPayment = CrowdSchemaPaymentScreen();
  static const schemaHistory = SchemaHistoryScreen();
  static const crowdSchemaHistory = CrowdSchemaHistoryScreen();
  static const payNow = PayNowScreen();
  static const reward = RewardsScreen();
  static const referral = ReferralScreen();
  static const settingsPasswordChange = SettingsPasswordChangeScreen();
  static const kyc = KycScreen();
  static const allNotification = NotificationScreen();
  static const allTransaction = AllTransaction();
  static const profileSettings = ProfileSettingsScreen();
  static const myTicket = MyTicketScreen();
  static const createNewTicket = AddNewTicket();
  static const emailVerificationOtp = EmailVerificationOtp();
  static const twoFaVerification = TwoFaVerification();
  static const twoFaVerificationOtp = TwoFaVerifyOtp();
}
